### ISSUE TITLE
GPTQv2 model doesn't load

### ISSUE THREAD

**Issue by s4rduk4r** [johnsmith0031/alpaca_lora_4bit#25] opened 2023-03-26 11:42 UTC
Basically header states the issue.

**Stacktrace throws:**
```python
Traceback (most recent call last):
  File "/home/user/alpaca_lora_4bit/inference.py", line 12, in <module>
    model, tokenizer = load_llama_model_4bit_low_ram(config_path, model_path)
  File "/home/user/alpaca_lora_4bit/./repository/GPTQ-for-LLaMa/autograd_4bit.py", line 220, in load_llama_model_4bit_low_ram
    model = accelerate.load_checkpoint_and_dispatch(model=model, checkpoint=model_path, device_map='auto')
  File "/home/user/.miniconda3/envs/llm/lib/python3.10/site-packages/accelerate/big_modeling.py", line 479, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/home/user/.miniconda3/envs/llm/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 862, in load_checkpoint_in_model
    set_module_tensor_to_device(model, param_name, param_device, value=param, dtype=dtype)
  File "/home/user/.miniconda3/envs/llm/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 131, in set_module_tensor_to_device
    raise ValueError(f"{module} does not have a parameter or a buffer named {tensor_name}.")
ValueError: Autograd4bitQuantLinear() does not have a parameter or a buffer named qzeros.
```

**How to reproduce:**
1. Download GPTQv2 model - https://huggingface.co/sardukar/llama13b-4bit-v2
2. In `inference.py` set `model_path = './llama-13b-4bit-v2.safetensors'`
3. `python inference.py`

**Intended behaviour:**
Model has to load and generate response

**How to check the model:**
1. Use [GPTQ-for-LLaMa](https://github.com/qwopqwop200/GPTQ-for-LLaMa) commit 841feedde876785bc8022ca48fd9c3ff626587e2
2. `CUDA_VISIBLE_DEVICES=0 python llama_inference.py ./llama-13b --wbits 4 --load ./q4/llama13b-4bit-v2.safetensors --text "AI can be explained as"`

**Complete setup below:**
```sh
(llm) user@computer:~/alpaca_lora_4bit$ git pull
Already up to date.
(llm) user@computer:~/alpaca_lora_4bit$ ll
total 128
drwxr-xr-x 10 user user  4096 Mar 26 14:17 ./
drwxr-x--- 12 user user  4096 Mar 26 14:17 ../
drwxr-xr-x  8 user user  4096 Mar 26 14:24 .git/
-rw-r--r--  1 user user    38 Mar 26 13:35 .gitignore
-rw-r--r--  1 user user  4498 Mar 26 13:35 Finetune4bConfig.py
drwxr-xr-x  2 user user  4096 Mar 26 13:35 GPTQ-for-LLaMa/
-rw-r--r--  1 user user  1067 Mar 26 13:35 LICENSE
-rw-r--r--  1 user user  1837 Mar 24 14:51 README.md
drwxr-xr-x  2 user user  4096 Mar 22 17:18 alpaca13b_lora/
drwxr-xr-x  2 user user  4096 Mar 26 09:58 alpaca_lora/
-rw-r--r--  1 user user  4714 Mar 26 13:35 arg_parser.py
-rw-r--r--  1 user user 19039 Mar 22 16:01 data.txt
lrwxrwxrwx  1 user user    41 Mar 24 12:29 dataset.json -> /mnt/e/ML/Alpaca13b/alpaca_data_tiny.json*
lrwxrwxrwx  1 user user    31 Mar 23 23:29 finetune-4b -> /mnt/e/ML/Alpaca13b/finetune-4b/
lrwxrwxrwx  1 user user    23 Mar 23 23:30 finetune-4b.py -> finetune-4b/finetune.py*
lrwxrwxrwx  1 user user    38 Mar 23 01:45 finetune-sad.py -> /mnt/e/ML/Alpaca13b/finetune-4b-sad.py*
-rw-r--r--  1 user user  4922 Mar 26 13:35 finetune.py
-rw-r--r--  1 user user  1547 Mar 26 14:17 inference.py
-rw-r--r--  1 user user  1269 Mar 24 14:51 install.bat
-rw-r--r--  1 user user  1330 Mar 24 14:51 install.sh
drwxr-xr-x  2 user user  4096 Mar 22 19:20 llama-13b-4bit/
lrwxrwxrwx  1 user user    61 Mar 26 13:42 llama-13b-4bit-v2.safetensors -> /mnt/e/ML/Alpaca13b/model/q4-new/llama13b-4bit-v2.safetensors*
lrwxrwxrwx  1 user user    43 Mar 22 21:11 llama-13b-4bit.pt -> /mnt/e/ML/Alpaca13b/model/llama-13b-4bit.pt*
drwxr-xr-x  3 user user  4096 Mar 22 16:01 peft/
drwxr-xr-x  5 user user  4096 Mar 22 16:02 repository/
-rw-r--r--  1 user user   186 Mar 22 16:01 requirements.txt
-rwxr--r--  1 user user    54 Mar 22 21:16 start-webui.sh*
drwxr-xr-x 13 user user  4096 Mar 26 14:02 text-generation-webui/
-rw-r--r--  1 user user  4566 Mar 26 13:35 train_data.py
```
```sh
(llm) user@computer:~/alpaca_lora_4bit$ head inference.py
```
```python
import os
import sys
sys.path.insert(0, './repository/transformers/src')
sys.path.insert(0, './repository/GPTQ-for-LLaMa')
sys.path.insert(0, './repository/peft/src')
import time
import torch
from autograd_4bit import load_llama_model_4bit_low_ram
config_path = './llama-13b-4bit/'
model_path = './llama-13b-4bit-v2.safetensors'
```
```sh
(llm) user@computer:~/alpaca_lora_4bit$ python inference.py
Loading Model ...
/home/user/.miniconda3/envs/llm/lib/python3.10/site-packages/accelerate/utils/modeling.py:696: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(checkpoint_file, framework="pt") as f:
/home/user/.miniconda3/envs/llm/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/home/user/.miniconda3/envs/llm/lib/python3.10/site-packages/torch/storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
The safetensors archive passed at ./llama-13b-4bit-v2.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
/home/user/.miniconda3/envs/llm/lib/python3.10/site-packages/safetensors/torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
Traceback (most recent call last):
  File "/home/user/alpaca_lora_4bit/inference.py", line 12, in <module>
    model, tokenizer = load_llama_model_4bit_low_ram(config_path, model_path)
  File "/home/user/alpaca_lora_4bit/./repository/GPTQ-for-LLaMa/autograd_4bit.py", line 220, in load_llama_model_4bit_low_ram
    model = accelerate.load_checkpoint_and_dispatch(model=model, checkpoint=model_path, device_map='auto')
  File "/home/user/.miniconda3/envs/llm/lib/python3.10/site-packages/accelerate/big_modeling.py", line 479, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/home/user/.miniconda3/envs/llm/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 862, in load_checkpoint_in_model
    set_module_tensor_to_device(model, param_name, param_device, value=param, dtype=dtype)
  File "/home/user/.miniconda3/envs/llm/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 131, in set_module_tensor_to_device
    raise ValueError(f"{module} does not have a parameter or a buffer named {tensor_name}.")
ValueError: Autograd4bitQuantLinear() does not have a parameter or a buffer named qzeros.
```

**Comment by Ph0rk0z** [comment] 2023-03-26 11:43
Hasn't been tested vs the new GPTQ yet

**Comment by s4rduk4r** [comment] 2023-03-26 11:46
I know. Just wanted to show what happens. Hope you'll be able to provide a fix soon

**Comment by johnsmith0031** [comment] 2023-03-27 09:58
Yes, will add V2 model support soon.

**Comment by Malfaro43** [comment] 2023-03-30 21:12
@s4rduk4r Is there a pytorch_model.bin.index.json for your [model](https://huggingface.co/sardukar/llama13b-4bit-v2)? When running finetune.py and passing the argument to a folder containing the files for the model, the code produces the error: "ValueError: model is not a folder containing a `.index.json` file."

**Comment by SentinelDev1** [comment] 2023-03-31 13:52
I'm also receiving the same "ValueError: Autograd4bitQuantLinear() does not have a parameter or a buffer named qzeros." error message when trying to run inference on a v2 model.  Has anyone found a workaround for this?

**Comment by johnsmith0031** [comment] 2023-03-31 15:58
Did you set group size? The default value is -1 and its for using V1 model

**Comment by SentinelDev1** [comment] 2023-03-31 16:06
I changed groupsize to 128 in the custom_monkey_patch file which seemed to resolve the above issue but for some reason getting the following error now:

`/home/sentinel/miniconda3/envs/alpaca4bit/lib/python3.10/site-packages/torch/storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
The safetensors archive passed at ../llama-30b-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
/home/sentinel/miniconda3/envs/alpaca4bit/lib/python3.10/site-packages/safetensors/torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
Loaded the model in 4.56 seconds.
Traceback (most recent call last):
  File "/home/sentinel/miniconda3/envs/alpaca4bit/lib/python3.10/site-packages/peft/utils/config.py", line 99, in from_pretrained
    config_file = hf_hub_download(pretrained_model_name_or_path, CONFIG_NAME)
  File "/home/sentinel/miniconda3/envs/alpaca4bit/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/sentinel/miniconda3/envs/alpaca4bit/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../alpaca-30b_lora/'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sentinel/alpaca_lora_4bit/text-generation-webui/server.py", line 276, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/sentinel/alpaca_lora_4bit/text-generation-webui/custom_monkey_patch.py", line 19, in load_model_llama
    model = PeftModel.from_pretrained(model, lora_path, device_map={'': 0}, torch_dtype=torch.float32)
  File "/home/sentinel/miniconda3/envs/alpaca4bit/lib/python3.10/site-packages/peft/peft_model.py", line 135, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[PeftConfig.from_pretrained(model_id).peft_type].from_pretrained(model_id)
  File "/home/sentinel/miniconda3/envs/alpaca4bit/lib/python3.10/site-packages/peft/utils/config.py", line 101, in from_pretrained
    raise ValueError(f"Can't find config.json at '{pretrained_model_name_or_path}'")
ValueError: Can't find config.json at '../alpaca-30b_lora/'`


I'm not sure why it's looking in the 'alpaca-30b_lora folder rather than the llama-30b-4bit folder mapped for config as seen below:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/122179833/229172383-57fb529d-9647-49d2-95ea-bc410c7fdf2d.png">

Even if I copy the config.json file from the llama-30b-4bit folder it still doesn't find it, not sure why.

**Comment by SentinelDev1** [comment] 2023-03-31 17:58
Yeah, that seemed to fix it, thanks!

**Comment by Tameflame** [comment] 2023-04-01 02:41
@johnsmith0031 adding groupsize to match the gptq groupsize solved that issue but now I'm getting this error:


```
  File "/root/miniconda3/envs/avo/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 131, in set_module_tensor_to_device
    raise ValueError(f"{module} does not have a parameter or a buffer named {tensor_name}.")
ValueError: Autograd4bitQuantLinear() does not have a parameter or a buffer named g_idx.
Traceback (most recent call last):
  File "/root/miniconda3/envs/avo/bin/accelerate-launch", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/avo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 921, in main
    launch_command(args)
  File "/root/miniconda3/envs/avo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 915, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/envs/avo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 578, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

**Comment by johnsmith0031** [comment] 2023-04-01 05:51
Maybe something changed in latest checkpoint. Will figure it out later.

**Comment by Jeduh** [comment] 2023-04-01 07:15
I'm getting 
`    raise ValueError(f"{module} does not have a parameter or a buffer named {tensor_name}.")
ValueError: Autograd4bitQuantLinear() does not have a parameter or a buffer named zeros.
`
should i wait or downgrade GPTQ?

**Comment by johnsmith0031** [comment] 2023-04-01 08:12
Change line 50 in autograd_4bit.py from
self.bias = nn.Parameter(torch.empty(outfeatures))
back to 
self.register_buffer('bias', torch.empty(outfeatures))
and see if it works.

**Comment by Jeduh** [comment] 2023-04-01 08:18
i still get the same 
ValueError: Autograd4bitQuantLinear() does not have a parameter or a buffer named zeros.

I'm using elinas/llama-30b-int4 in finetune.py

**Comment by johnsmith0031** [comment] 2023-04-01 08:23
try setting group size = -1

**Comment by Jeduh** [comment] 2023-04-01 08:25
works fine but that's because its using v1 right?

**Comment by Tameflame** [comment] 2023-04-01 08:33
@johnsmith0031 

> Change line 50 in autograd_4bit.py from
> 
> ```
> self.bias = nn.Parameter(torch.empty(outfeatures))
> ```
> 
> back to
> 
> ```
> self.register_buffer('bias', torch.empty(outfeatures))
> ```
> 
> and see if it works.
> 
> And also, which checkpoint did you use? I may need to reproduce it with my own code.

This doesn't help, still getting:

`ValueError: Autograd4bitQuantLinear() does not have a parameter or a buffer named g_idx.`

I'll see if I can upload my checkpoint, but it's just the base 7b decapoda/huggingface model which I quantize myself with qwopqwop200/GPTQ-for-LLaMa.

**Comment by Tameflame** [comment] 2023-04-01 08:38
@johnsmith0031 

Ok got looks like I got it working by:

>Change line 50 in autograd_4bit.py from
>`self.bias = nn.Parameter(torch.empty(outfeatures))`
>back to
>`self.register_buffer('bias', torch.empty(outfeatures))`

AND

>insert after line 50
>`self.register_buffer('g_idx', torch.empty(outfeatures))`

It seems to be running now so let's see if it completes. If all good I'll report back here

**Comment by johnsmith0031** [comment] 2023-04-01 08:40
> @johnsmith0031
> 
> > Change line 50 in autograd_4bit.py from
> > ```
> > self.bias = nn.Parameter(torch.empty(outfeatures))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > back to
> > ```
> > self.register_buffer('bias', torch.empty(outfeatures))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and see if it works.
> > And also, which checkpoint did you use? I may need to reproduce it with my own code.
> 
> This doesn't help, still getting:
> 
> `ValueError: Autograd4bitQuantLinear() does not have a parameter or a buffer named g_idx.`
> 
> I'll see if I can upload my checkpoint, but it's just the base 7b decapoda/huggingface model which I quantize myself with qwopqwop200/GPTQ-for-LLaMa.

Thanks! I think they've made some changes in the format of checkpoint. It seems that they have a new parameter g_idx in it.
You can try to load the checkpoint yourself and check the shape of g_idx, and add a line in Autograd4bitQuantLinear class just like:

```
self.register_buffer('g_idx', torch.empty(shape))
```
And I think it will work.

**Comment by Jeduh** [comment] 2023-04-01 08:44
ValueError: Autograd4bitQuantLinear() does not have a parameter or a buffer named zeros.

still outputs this for fine tuning with the included changes

**Comment by johnsmith0031** [comment] 2023-04-01 12:00
I think setting group size to -1 would solve the problem because only V1 model use zeros and V2 model use qzeros.

**Comment by s4rduk4r** [comment] 2023-04-01 17:15
Maybe the best way would be to introduce a new key. Something like --gptq with values 1 and 2 with 1 being default. If the version is 2, then groupsize has to be set equal to infeatures, like it happens [here](https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/5955e9c67d9bfe8a8144ffbe853c2769f1e87cdd/quant.py#L255) and register a 'qzeros' torch buffer instead of 'zeros' as it happens [here](https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/5955e9c67d9bfe8a8144ffbe853c2769f1e87cdd/quant.py#L259). Unfortunately I don't have much time right now to test it myself. Would appreciate if someone can try and report results here

**Comment by Tameflame** [comment] 2023-04-01 17:47
@johnsmith0031 Hey so training failed, it was running without and error but I noticed loss was at 0.0 which I think means the model was failing during training.

I tried just setting group size to -1 and quantizing again, but then trying to train gave me a qzeros not found error. Resolved it by adding self.register_buffer('qzeros) in the if statement in autograd_4bit but that just gave another error: "RuntimeError: Trying to create tensor with negative dimension -4096: [-4096, 512]"

I guess at this point I'll just stick to v1 quantizing and try again, is there a specific repo I can do that with?

**Comment by johnsmith0031** [comment] 2023-04-02 03:02
Not sure if gptq support V1 quantizing now, will investigate into it
And If you're training with v2 model you can simply pass --groupsize=128 to finetune.py instead of adding self.register_buffer('qzeros')

**Comment by Tameflame** [comment] 2023-04-02 03:44
@johnsmith0031 

Setting grousize=128 works, but I think the training is wrong, because it shows loss as 0.0. I'm not sure why.
![image](https://user-images.githubusercontent.com/26692217/229330092-259cdf8a-f0af-43a8-acff-03a5fa786a9f.png)

**Comment by johnsmith0031** [comment] 2023-04-02 05:04
Did you removed the line self.register_buffer('qzeros') you added? It would overwrite the original weight in checkpoint

**Comment by Ph0rk0z** [comment] 2023-04-02 14:15
I think GPTQ changed things yet again.

**Comment by s4rduk4r** [comment] 2023-04-03 19:51
> Maybe the best way would be to introduce a new key. Something like --gptq with values 1 and 2 with 1 being default. If the version is 2, then groupsize has to be set equal to infeatures, like it happens [here](https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/5955e9c67d9bfe8a8144ffbe853c2769f1e87cdd/quant.py#L255) and register a 'qzeros' torch buffer instead of 'zeros' as it happens [here](https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/5955e9c67d9bfe8a8144ffbe853c2769f1e87cdd/quant.py#L259). Unfortunately I don't have much time right now to test it myself. Would appreciate if someone can try and report results here

I've tried this idea and got to work finetune, but also have 0.0 loss. My theory is that `qzeros` buffer stores its values differently  in comparison to `zeros`, because I had to explicitly convert it to `int` in `autograd_4bit.py` during the forward pass. Probably during conversion values are being trimmed. Alternatively, this buffer loses its values somewhere during the load. Although against the last statement is the fact that inference seems to be okay

Also, I've noticed that GPTQv2 models seems to consume more VRAM than GPTQv1
![изображение](https://user-images.githubusercontent.com/15340708/229610288-abcee926-3c50-4589-aa57-4abb0badc2d4.png)

**Comment by johnsmith0031** [comment] 2023-04-04 08:28
qzeros store the zeros in 4bit (which is originally fp16) for different groups, and it only works with v2 model (groupsize != -1). If you're using v1 model please set groupsize=-1, or it would fail.

**Comment by Tameflame** [comment] 2023-04-04 13:22
@johnsmith0031 Heys so I'm still trying to get v2 to work but still get the issue of 0.0 loss during finetuning.

I did a _fresh clone_ today of your repo, and the only changes I made are to autograd_4bit.py to replace self.bias = nn.Parameter(torch.empty(outfeatures)) with self.register_buffer('bias', torch.empty(outfeatures)). [Without that change finetuning would exit with an error about the bias not being set]

The finetune runs **but** it keeps giving 0.0 loss.

![image](https://user-images.githubusercontent.com/26692217/229805857-9ca4091e-4d8b-4fdd-ac2a-7d66805d48d9.png)

**Comment by s4rduk4r** [comment] 2023-04-05 23:56
@johnsmith0031 I've managed to load and train a model. Before I'll make a pull request I need you to check if your code is compatible with what I've done. It uses fixed triton kernels from `triton_utils.py`. Below is the screenshot of GPTQv2 model training on `data.txt`
Link to solution - https://github.com/s4rduk4r/alpaca_lora_4bit

Also, it would be really nice if your peft/lora version would include some sort of an abstract class to inherit from. Because right now in order to make my code backward compatible I had to introduce environmental variable which is not the most elegant solution. Maybe some of you guys will refactor it better

![изображение](https://user-images.githubusercontent.com/15340708/230238520-94d2f1ec-747f-4d62-93ba-4305e1f65a85.png)

**Comment by johnsmith0031** [comment] 2023-04-06 01:40
Thanks! I'll see if I can merge the solution

**Comment by johnsmith0031** [comment] 2023-04-06 05:50
Tried the models from this magnet-link below on runpod, but still cannot reproduce the bug.
magnet:?xt=urn:btih:RD35TUSGB76K66FSD2BQCLPABE46VS3F&dn=LLaMA-HF-4bit-128g&tr=http%3A%2F%2Fbt2.archive.org%3A6969%2Fannounce&tr=http%3A%2F%2Fbt1.archive.org%3A6969%2Fannounce&xl=65238528057

**Comment by johnrobinsn** [comment] 2023-04-06 14:15
@Tameflame were you able to get past the loss 0.0 issue?  Thx much

**Comment by johnsmith0031** [comment] 2023-04-07 08:39
Merged triton backend from s4rduk4r's fork for supporting v2 model with --true-sequential and --act-order.

**Comment by Tameflame** [comment] 2023-04-07 09:13
> @Tameflame were you able to get past the loss 0.0 issue? Thx much

Yes. I used gptq to convert into .safetensors file. Afterwards it worked without any problems.

**Comment by s4rduk4r** [comment] 2023-04-07 18:25
> Merged triton backend from s4rduk4r's fork for supporting v2 model with --true-sequential and --act-order.

Should I close this issue then or better to wait until the CUDA implementation?

**Comment by johnsmith0031** [comment] 2023-04-08 03:07
I think currently we've done with this issue, If having any other problems we can open a new issue for cuda implementation. Again, thanks for your contribution.

**Closed by johnsmith0031** 2023-04-08 03:07 UTC
